#==============================================================================#
#                       Snakemake Configuration (config.yaml)                  #
#==============================================================================#

#==============================================================================#
#                                    Global                                    #
#==============================================================================#

# --- Sample Definitions ---
# List of assembly IDs to process.
assemblies_to_process:
  - "ECBPP6_20220826_contigs"
  - "SitukuyokBP_2023_contigs"
  - "TKL807_20230823_contigs"
  - "WCBP1P2_20230826_contigs"
  - "RCBP2P4_20220823_contigs"
  - "TKL524_20230828_contigs"
  - "TKL873_20230823_contigs"
  - "WCBP1P4_20230826_contigs"

# Directory for assemblies.
assemblies_dir: "/tank/data/LS/petersob/metagenomes/AK/assemblies"

# Home directory for the workflow.
home_dir: "/tank/data/LS/petersob/petersob/AK"
# Directory where all processed data will be stored
data_temp: "data_temp"
# Directory where all final data will be stored
data_final: "data_final"

# Apptainer container names
pyrodigal_container: "/tank/data/LS/petersob/containers/pyrodigal.sif"
hmmer_container: "/tank/data/LS/petersob/containers/hmmer.sif"

# Wrapper scripts. Relative to PLBS.
plbs_dir: "/tank/data/LS/petersob/Peterson_Lab_Bioinformatics_Scaffold"
pyrodigal_wrapper_script: "executables/MGassemblyAnnotation/annotate_MGassembly_ORFs_pyrodigal.py"
hmm_search_script: "executables/MGassemblyAnnotation/annotate_MGassembly_HMMsearch.py"

# HMM resources (relative to PLBS_DIR)
hgca_hmm: "resources/HMMs/hgcA"

#==============================================================================#
#                           Pyrodigal Parameters                               #
#==============================================================================#
pyrodigal_output_format: "gff"
pyrodigal_procedure: "meta"

#==============================================================================#
#                         HMM Search Parameters                                #
#==============================================================================#
hmm_cutoff_type: "cut_tc"  # Use trusted cutoff from HMM model


# config.yaml
slurm-jobstep: false